# Generated by Django 4.2.7 on 2024-06-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrs_api', '0002_remove_riotapiversion_name_riotapiversion_asset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summonerspell',
            name='name',
            field=models.CharField(max_length=35),
        ),
    ]
