# Generated by Django 4.2.7 on 2024-06-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrs_api', '0003_alter_summonerspell_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemode',
            name='name',
            field=models.CharField(max_length=45),
        ),
    ]
