        migrations.RunSQL(
            sql="""
            ---remove everything after NOT NULL on "id" (PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY), create partition, add partitions, insert partitions after foreign key constraint, add composite PK
            --- at the momenent issue bc id has to be specified, which we dont want                 "id" bigint NOT NULL,
            --- CHANGE id to SERIAL NOT NULL
            CREATE TABLE "wrs_api_summoner" (
                "id" SERIAL NOT NULL,
                "puuid" varchar(100) NOT NULL,
                "gameName" varchar(50) NOT NULL,
                "tagLine" varchar(10) NOT NULL,
                "profileIconId" integer NOT NULL,
                "encryptedSummonerId" varchar(100) NOT NULL,
                "most_recent_game" varchar(25),
                "created_at" timestamp with time zone NOT NULL,
                "updated_at" timestamp with time zone NOT NULL,
                "platform" varchar NOT NULL,
	            PRIMARY KEY (platform, puuid)
            ) PARTITION BY LIST (platform);

            ALTER TABLE "wrs_api_summoner" ADD CONSTRAINT "wrs_api_summoner_platform_39a7e8f3_fk_wrs_api_platform_code" FOREIGN KEY ("platform") REFERENCES "wrs_api_platform" ("code") DEFERRABLE INITIALLY DEFERRED;

            CREATE TABLE wrs_api_summoner_na1 PARTITION OF wrs_api_summoner FOR VALUES IN ('na1');
            CREATE TABLE wrs_api_summoner_euw1 PARTITION OF wrs_api_summoner FOR VALUES IN ('euw1');

            CREATE INDEX "wrs_api_summoner_puuid_ec1c8f0f_like" ON "wrs_api_summoner" ("puuid" varchar_pattern_ops);
            CREATE INDEX "wrs_api_summoner_platform_39a7e8f3" ON "wrs_api_summoner" ("platform");
            CREATE INDEX "wrs_api_summoner_platform_39a7e8f3_like" ON "wrs_api_summoner" ("platform" varchar_pattern_ops);

            INSERT INTO wrs_api_platform (code) VALUES ("tr1"), ("ph2"), ("la1"), ("tw2"), ("la2"), ("eun1"), ("vn2"), ("kr"), ("oc1"), ("na1"), ("jp1"), ("euw1"), ("sg2"), ("ru"), ("th2"), ("br1");

            """
        )










        migrations.RunSQL(
            """
                CREATE TABLE "wrs_api_summoner" (
                    "id" SERIAL NOT NULL,
                    "puuid" varchar(100) NOT NULL,
                    "gameName" varchar(50) NOT NULL,
                    "tagLine" varchar(10) NOT NULL,
                    "profileIconId" integer NOT NULL,
                    "encryptedSummonerId" varchar(100) NOT NULL,
                    "most_recent_game" varchar(25) NULL,
                    "created_at" timestamp with time zone NOT NULL,
                    "updated_at" timestamp with time zone NOT NULL,
                    "platform" varchar NOT NULL,
                    PRIMARY KEY (platform, puuid)
                ) PARTITION BY LIST (platform);


                ALTER TABLE "wrs_api_summoner" ADD CONSTRAINT "wrs_api_summoner_puuid_platform_c4182f4c_uniq" UNIQUE ("puuid", "platform");
                ALTER TABLE "wrs_api_summoner" ADD CONSTRAINT "wrs_api_summoner_platform_39a7e8f3_fk_wrs_api_platform_code" FOREIGN KEY ("platform")

                CREATE TABLE wrs_api_summoner_na1 PARTITION OF wrs_api_summoner FOR VALUES IN ('na1');
                CREATE TABLE wrs_api_summoner_euw1 PARTITION OF wrs_api_summoner FOR VALUES IN ('euw1');
  
                CREATE INDEX "wrs_api_summoner_puuid_ec1c8f0f_like" ON "wrs_api_summoner" ("puuid" varchar_pattern_ops);
                CREATE INDEX "wrs_api_summoner_platform_39a7e8f3" ON "wrs_api_summoner" ("platform");
                CREATE INDEX "wrs_api_summoner_platform_39a7e8f3_like" ON "wrs_api_summoner" ("platform" varchar_pattern_ops);

                INSERT INTO wrs_api_platform (code) VALUES ("tr1"), ("ph2"), ("la1"), ("tw2"), ("la2"), ("eun1"), ("vn2"), ("kr"), ("oc1"), ("na1"), ("jp1"), ("euw1"), ("sg2"), ("ru"), ("th2"), ("br1");

            """
        )





working migration:
# Generated by Django 4.2.7 on 2024-03-19 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puuid', models.CharField(max_length=100)),
                ('gameName', models.CharField(max_length=50)),
                ('tagLine', models.CharField(max_length=10)),
                ('profileIconId', models.IntegerField()),
                ('encryptedSummonerId', models.CharField(max_length=100)),
                ('most_recent_game', models.CharField(max_length=25, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wrs_api_summoner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('championId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('queueId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LegendaryItem',
            fields=[
                ('itemId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('code', models.CharField(choices=[('na1', 'na1'), ('euw1', 'euw1'), ('br1', 'br1')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('name', models.CharField(choices=[('americas', 'americas'), ('asia', 'asia'), ('europe', 'europe'), ('sea', 'sea')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('split', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TierTwoBoot',
            fields=[
                ('itemId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('full_version', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=6)),
                ('season', models.ForeignKey(db_column='season', on_delete=django.db.models.deletion.CASCADE, to='wrs_api.season')),
            ],
        ),
        migrations.RunSQL(
            """
                CREATE TABLE "wrs_api_summoner" (
                    "id" SERIAL NOT NULL,
                    "puuid" varchar(100) NOT NULL,
                    "gameName" varchar(50) NOT NULL,
                    "tagLine" varchar(10) NOT NULL,
                    "profileIconId" integer NOT NULL,
                     "encryptedSummonerId" varchar(100) NOT NULL,
                    "most_recent_game" varchar(25) NULL,
                    "created_at" timestamp with time zone NOT NULL,
                    "updated_at" timestamp with time zone NOT NULL,
                    "platform" varchar NOT NULL,
                    PRIMARY KEY (platform, puuid)
                ) PARTITION BY LIST (platform);


                ALTER TABLE "wrs_api_summoner" ADD CONSTRAINT "wrs_api_summoner_puuid_platform_c4182f4c_uniq" UNIQUE ("puuid", "platform");
                ALTER TABLE "wrs_api_summoner" ADD CONSTRAINT "wrs_api_summoner_platform_39a7e8f3_fk_wrs_api_platform_code" FOREIGN KEY ("platform") REFERENCES "wrs_api_platform" ("code") DEFERRABLE INITIALLY DEFERRED;

                CREATE TABLE wrs_api_summoner_na1 PARTITION OF wrs_api_summoner FOR VALUES IN ('na1');
                CREATE TABLE wrs_api_summoner_euw1 PARTITION OF wrs_api_summoner FOR VALUES IN ('euw1');
                CREATE TABLE wrs_api_summoner_br1 PARTITION OF wrs_api_summoner FOR VALUES IN ('br1');


                CREATE INDEX "wrs_api_summoner_puuid_ec1c8f0f_like" ON "wrs_api_summoner" ("puuid" varchar_pattern_ops);
                CREATE INDEX "wrs_api_summoner_platform_39a7e8f3" ON "wrs_api_summoner" ("platform");
                CREATE INDEX "wrs_api_summoner_platform_39a7e8f3_like" ON "wrs_api_summoner" ("platform" varchar_pattern_ops);

                ---INSERT INTO wrs_api_platform (code) VALUES ("tr1"), ("ph2"), ("la1"), ("tw2"), ("la2"), ("eun1"), ("vn2"), ("kr"), ("oc1"), ("na1"), ("jp1"), ("euw1"), ("sg2"), ("ru"), ("th2"), ("br1");
                INSERT INTO wrs_api_platform (code) VALUES ('na1'), ('euw1'), ('br1');

            """
        )
    ]
