 migrations.RunSQL(
            """
            ---remove everything after NOT NULL on "id" (PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY), create partition, add partitions, insert partitions after foreign key constraint, add composite PK
            --- at the momenent issue bc id has to be specified, which we dont want                 "id" bigint NOT NULL,
            --- CHANGE id to SERIAL NOT NULL
            --- make all ALTER TABLES part of the table definition
            --- ADD ON DELETE CASCADE to all FOREIGN KEYS

                CREATE TABLE "wrs_api_summoner" (
                    "id" SERIAL NOT NULL,
                    "puuid" varchar(100) NOT NULL,
                    "gameName" varchar(50) NOT NULL,
                    "tagLine" varchar(10) NOT NULL,
                    "profileIconId" integer NOT NULL,
                     "encryptedSummonerId" varchar(100) NOT NULL,
                    "most_recent_game" varchar(25) NULL,
                    "created_at" timestamp with time zone NOT NULL,
                    "updated_at" timestamp with time zone NOT NULL,
                    "platform" varchar NOT NULL,
                    FOREIGN KEY ("platform") REFERENCES wrs_api_platform ("code") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                    CONSTRAINT "wrs_api_summoner_puuid_platform_c4182f4c_uniq" UNIQUE ("puuid", "platform"),
                    PRIMARY KEY (platform, puuid)
                ) PARTITION BY LIST (platform);


                ---ALTER TABLE "wrs_api_summoner" ADD CONSTRAINT "wrs_api_summoner_puuid_platform_c4182f4c_uniq" UNIQUE ("puuid", "platform");
                ---ALTER TABLE "wrs_api_summoner" ADD CONSTRAINT "wrs_api_summoner_platform_39a7e8f3_fk_wrs_api_platform_code" FOREIGN KEY ("platform") REFERENCES "wrs_api_platform" ("code") DEFERRABLE INITIALLY DEFERRED;

                CREATE TABLE wrs_api_summoner_na1 PARTITION OF wrs_api_summoner FOR VALUES IN ('na1');
                CREATE TABLE wrs_api_summoner_euw1 PARTITION OF wrs_api_summoner FOR VALUES IN ('euw1');
                CREATE TABLE wrs_api_summoner_br1 PARTITION OF wrs_api_summoner FOR VALUES IN ('br1');


                CREATE INDEX "wrs_api_summoner_puuid_ec1c8f0f_like" ON "wrs_api_summoner" ("puuid" varchar_pattern_ops);
                CREATE INDEX "wrs_api_summoner_platform_39a7e8f3" ON "wrs_api_summoner" ("platform");
                CREATE INDEX "wrs_api_summoner_platform_39a7e8f3_like" ON "wrs_api_summoner" ("platform" varchar_pattern_ops);

                ---INSERT INTO wrs_api_platform (code) VALUES ("tr1"), ("ph2"), ("la1"), ("tw2"), ("la2"), ("eun1"), ("vn2"), ("kr"), ("oc1"), ("na1"), ("jp1"), ("euw1"), ("sg2"), ("ru"), ("th2"), ("br1");
                INSERT INTO wrs_api_platform (code) VALUES ('na1'), ('euw1'), ('br1');

            """
        ),
        migrations.RunSQL(
            """
                --- OVERVIEWS
                CREATE TABLE "wrs_api_summoneroverview" (
                "id" SERIAL NOT NULL,
                "puuid" varchar(100) NOT NULL,
                "platform" varchar NOT NULL, 
                "season_id" bigint NOT NULL, 
                "metadata" jsonb NOT NULL,
                "created_at" timestamp with time zone NOT NULL,
                "updated_at" timestamp with time zone NOT NULL,
                FOREIGN KEY (platform, puuid) REFERENCES wrs_api_summoner (platform, puuid) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                FOREIGN KEY (season_id) REFERENCES wrs_api_season (id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                FOREIGN KEY ("platform") REFERENCES wrs_api_platform ("code") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                CONSTRAINT "wrs_api_summoneroverview_season_id_summoner_id_pl_1da9a9db_uniq" UNIQUE ("season_id", "puuid", "platform"),
                PRIMARY KEY (puuid, season_id, platform)
                ) PARTITION BY LIST (platform);
                

                ---ALTER TABLE "wrs_api_summoneroverview" 
                ---    ADD CONSTRAINT "wrs_api_summoneroverview_season_id_summoner_id_pl_1da9a9db_uniq" UNIQUE ("season_id", "puuid", "platform");
                ---ALTER TABLE "wrs_api_summoneroverview" 
                ---    ADD CONSTRAINT "wrs_api_summonerover_platform_99315587_fk_wrs_api_p" FOREIGN KEY ("platform") REFERENCES "wrs_api_platform" ("code") DEFERRABLE INITIALLY DEFERRED;

                CREATE TABLE wrs_api_summoneroverview_na1 PARTITION OF wrs_api_summoneroverview FOR VALUES IN ('na1');
                CREATE TABLE wrs_api_summoneroverview_euw1 PARTITION OF wrs_api_summoneroverview FOR VALUES IN ('euw1');
                CREATE TABLE wrs_api_summoneroverview_br1 PARTITION OF wrs_api_summoneroverview FOR VALUES IN ('br1');

                -- ALTER TABLE "wrs_api_summoneroverview" ADD CONSTRAINT "wrs_api_summonerover_season_id_4cf689b6_fk_wrs_api_s" FOREIGN KEY ("puuid") REFERENCES "wrs_api_season" ("id") DEFERRABLE INITIALLY DEFERRED;
                -- ALTER TABLE "wrs_api_summoneroverview" ADD CONSTRAINT "wrs_api_summonerover_summoner_id_4f6afb74_fk_wrs_api_s" FOREIGN KEY ("summoner_id") REFERENCES "wrs_api_summoner" ("id") DEFERRABLE INITIALLY DEFERRED;

                CREATE INDEX "wrs_api_summoneroverview_platform_99315587" ON "wrs_api_summoneroverview" ("platform");

                CREATE INDEX "wrs_api_summoneroverview_platform_99315587_like" ON "wrs_api_summoneroverview" ("platform" varchar_pattern_ops);

                -- CREATE INDEX "wrs_api_summoneroverview_season_id_4cf689b6" ON "wrs_api_summoneroverview" ("season_id");

                CREATE INDEX "wrs_api_summoneroverview_summoner_id_4f6afb74" ON "wrs_api_summoneroverview" ("puuid");
            """
        ),
        migrations.RunSQL(
            """
            --- belongs to queue, patch, season, platform
            ---partioned on platform
                CREATE TABLE "wrs_api_match" (
                    "id" SERIAL NOT NULL,
                    "matchId" varchar(20) NOT NULL, 
                    "queueId" integer NOT NULL, 
                    "season_id" bigint NOT NULL,
                    "patch_id" varchar(25) NOT NULL, 
                    "platform" varchar NOT NULL, 
                    "metadata" jsonb NOT NULL, 
                    PRIMARY KEY ("platform", "matchId"),
                    FOREIGN KEY ("queueId") REFERENCES wrs_api_gamemode ("queueId") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                    FOREIGN KEY ("patch_id") REFERENCES wrs_api_patch ("full_version") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                    FOREIGN KEY ("season_id") REFERENCES wrs_api_season ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                    FOREIGN KEY ("platform") REFERENCES "wrs_api_platform" ("code") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
                ) PARTITION BY LIST ("platform");


                CREATE TABLE wrs_api_match_na1 PARTITION OF wrs_api_match FOR VALUES IN ('na1');
                CREATE TABLE wrs_api_match_euw1 PARTITION OF wrs_api_match FOR VALUES IN ('euw1');
                CREATE TABLE wrs_api_match_br1 PARTITION OF wrs_api_match FOR VALUES IN ('br1');

                CREATE INDEX "wrs_api_match_patch_id_0b245097" ON "wrs_api_match" ("patch_id");
                CREATE INDEX "wrs_api_match_patch_id_0b245097_like" ON "wrs_api_match" ("patch_id" varchar_pattern_ops);
                CREATE INDEX "wrs_api_match_platform_2b2c1736" ON "wrs_api_match" ("platform");
                CREATE INDEX "wrs_api_match_platform_2b2c1736_like" ON "wrs_api_match" ("platform" varchar_pattern_ops);
                CREATE INDEX "wrs_api_match_queueId_id_28ffec5b" ON "wrs_api_match" ("queueId");
                CREATE INDEX "wrs_api_match_season_id_996a93bd" ON "wrs_api_match" ("season_id");

            """
        ),
        migrations.RunSQL(
            """
            CREATE TABLE "wrs_api_match_summoners" (
                ---"id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
                "id" SERIAL NOT NULL,
                "matchId" varchar(20) NOT NULL, 
                "puuid" varchar(100) NOT NULL,
                "platform" varchar NOT NULL,
                FOREIGN KEY ("platform", "matchId") REFERENCES wrs_api_match ("platform", "matchId") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                FOREIGN KEY ("platform", "puuid") REFERENCES wrs_api_summoner ("platform", "puuid") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                FOREIGN KEY ("platform") REFERENCES "wrs_api_platform" ("code") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                CONSTRAINT "wrs_api_match_summoners_matchId_puuid_id_33a445ac_uniq" UNIQUE ("matchId", "puuid", "platform"),
                PRIMARY KEY ("platform", "matchId", "puuid")
            ) PARTITION BY LIST (platform);

            
            ---ALTER TABLE "wrs_api_match_summoners" 
            ---    ADD CONSTRAINT "wrs_api_match_summoners_matchId_puuid_id_33a445ac_uniq" 
            ---    UNIQUE ("matchId", "puuid", "platform");

            CREATE TABLE wrs_api_match_summoners_na1 PARTITION OF wrs_api_match_summoners FOR VALUES IN ('na1');
            CREATE TABLE wrs_api_match_summoners_euw1 PARTITION OF wrs_api_match_summoners FOR VALUES IN ('euw1');
            CREATE TABLE wrs_api_match_summoners_kr1 PARTITION OF wrs_api_match_summoners FOR VALUES IN ('br1');

            CREATE INDEX "wrs_api_match_summoners_matchId_d9b8b076" ON "wrs_api_match_summoners" ("matchId");
            CREATE INDEX "wrs_api_match_summoners_puuid_1a034af0" ON "wrs_api_match_summoners" ("puuid");
             """
        ),