        migrations.RunSQL(
            sql="""
            ---remove everything after NOT NULL on "id" (PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY), create partition, add partitions, insert partitions after foreign key constraint, add composite PK
            --- at the momenent issue bc id has to be specified, which we dont want                 "id" bigint NOT NULL,
            --- CHANGE id to SERIAL NOT NULL
            CREATE TABLE "wrs_api_summoner" (
                "id" SERIAL NOT NULL,
                "puuid" varchar(100) NOT NULL,
                "gameName" varchar(50) NOT NULL,
                "tagLine" varchar(10) NOT NULL,
                "profileIconId" integer NOT NULL,
                "encryptedSummonerId" varchar(100) NOT NULL,
                "most_recent_game" varchar(25),
                "created_at" timestamp with time zone NOT NULL,
                "updated_at" timestamp with time zone NOT NULL,
                "platform" varchar NOT NULL,
	            PRIMARY KEY (platform, puuid)
            ) PARTITION BY LIST (platform);

            ALTER TABLE "wrs_api_summoner" ADD CONSTRAINT "wrs_api_summoner_platform_39a7e8f3_fk_wrs_api_platform_code" FOREIGN KEY ("platform") REFERENCES "wrs_api_platform" ("code") DEFERRABLE INITIALLY DEFERRED;

            CREATE TABLE wrs_api_summoner_na1 PARTITION OF wrs_api_summoner FOR VALUES IN ('na1');
            CREATE TABLE wrs_api_summoner_euw1 PARTITION OF wrs_api_summoner FOR VALUES IN ('euw1');

            CREATE INDEX "wrs_api_summoner_puuid_ec1c8f0f_like" ON "wrs_api_summoner" ("puuid" varchar_pattern_ops);
            CREATE INDEX "wrs_api_summoner_platform_39a7e8f3" ON "wrs_api_summoner" ("platform");
            CREATE INDEX "wrs_api_summoner_platform_39a7e8f3_like" ON "wrs_api_summoner" ("platform" varchar_pattern_ops);

            INSERT INTO wrs_api_platform (code) VALUES ("tr1"), ("ph2"), ("la1"), ("tw2"), ("la2"), ("eun1"), ("vn2"), ("kr"), ("oc1"), ("na1"), ("jp1"), ("euw1"), ("sg2"), ("ru"), ("th2"), ("br1");

            """
        )










        migrations.RunSQL(
            """
                CREATE TABLE "wrs_api_summoner" (
                    "id" SERIAL NOT NULL,
                    "puuid" varchar(100) NOT NULL,
                    "gameName" varchar(50) NOT NULL,
                    "tagLine" varchar(10) NOT NULL,
                    "profileIconId" integer NOT NULL,
                    "encryptedSummonerId" varchar(100) NOT NULL,
                    "most_recent_game" varchar(25) NULL,
                    "created_at" timestamp with time zone NOT NULL,
                    "updated_at" timestamp with time zone NOT NULL,
                    "platform" varchar NOT NULL,
                    PRIMARY KEY (platform, puuid)
                ) PARTITION BY LIST (platform);


                ALTER TABLE "wrs_api_summoner" ADD CONSTRAINT "wrs_api_summoner_puuid_platform_c4182f4c_uniq" UNIQUE ("puuid", "platform");
                ALTER TABLE "wrs_api_summoner" ADD CONSTRAINT "wrs_api_summoner_platform_39a7e8f3_fk_wrs_api_platform_code" FOREIGN KEY ("platform")

                CREATE TABLE wrs_api_summoner_na1 PARTITION OF wrs_api_summoner FOR VALUES IN ('na1');
                CREATE TABLE wrs_api_summoner_euw1 PARTITION OF wrs_api_summoner FOR VALUES IN ('euw1');
  
                CREATE INDEX "wrs_api_summoner_puuid_ec1c8f0f_like" ON "wrs_api_summoner" ("puuid" varchar_pattern_ops);
                CREATE INDEX "wrs_api_summoner_platform_39a7e8f3" ON "wrs_api_summoner" ("platform");
                CREATE INDEX "wrs_api_summoner_platform_39a7e8f3_like" ON "wrs_api_summoner" ("platform" varchar_pattern_ops);

                INSERT INTO wrs_api_platform (code) VALUES ("tr1"), ("ph2"), ("la1"), ("tw2"), ("la2"), ("eun1"), ("vn2"), ("kr"), ("oc1"), ("na1"), ("jp1"), ("euw1"), ("sg2"), ("ru"), ("th2"), ("br1");

            """
        )