# Generated by Django 4.2.7 on 2024-04-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrs_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('picked', models.IntegerField()),
                ('banned', models.IntegerField()),
            ],
            options={
                'db_table': 'wrs_api_championstat',
                'managed': False,
            },
        ),
        migrations.RunSQL(
            """
                CREATE TABLE "wrs_api_championstat" (
                    "id" SERIAL NOT NULL,
                    "wins" INTEGER NOT NULL,
                    "losses" INTEGER NOT NULL,
                    "picked" INTEGER NOT NULL,
                    "banned" INTEGER NOT NULL,
                    "championId" INTEGER NOT NULL,
                    "patch" VARCHAR(25) NOT NULL,
                    "platform" VARCHAR NOT NULL,
                    "season_id" BIGINT NOT NULL,
                    CONSTRAINT wrs_api_championstat_championId_platform_pat_ac3045bd_uniq UNIQUE ("championId", "platform", "patch"),
                    FOREIGN KEY ("championId") REFERENCES wrs_api_champion ("championId") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                    FOREIGN KEY ("patch") REFERENCES wrs_api_patch ("full_version") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                    FOREIGN KEY ("platform") REFERENCES wrs_api_platform ("code") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                    FOREIGN KEY ("season_id") REFERENCES wrs_api_season ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                    PRIMARY KEY ("platform","championId","patch")
                ) PARTITION BY LIST ("platform");

                ---ALTER TABLE wrs_api_championstat 
                    ---ADD CONSTRAINT wrs_api_championstat_championId_platform_pat_ac3045bd_uniq UNIQUE (championId, platform, patch);
                    ---ADD CONSTRAINT wrs_api_championstat_champion_id_c231a738_fk_wrs_api_c FOREIGN KEY (champion_id) REFERENCES wrs_api_champion (championId) DEFERRABLE INITIALLY DEFERRED,
                    ---ADD CONSTRAINT wrs_api_championstat_patch_db5180eb_fk_wrs_api_p FOREIGN KEY (patch) REFERENCES wrs_api_patch (full_version) DEFERRABLE INITIALLY DEFERRED,
                    ---ADD CONSTRAINT wrs_api_championstat_platform_88d7ca7a_fk_wrs_api_platform_code FOREIGN KEY (platform) REFERENCES wrs_api_platform (code) DEFERRABLE INITIALLY DEFERRED,
                    ---ADD CONSTRAINT wrs_api_championstat_season_id_24005562_fk_wrs_api_season_id FOREIGN KEY (season_id) REFERENCES wrs_api_season (id) DEFERRABLE INITIALLY DEFERRED;

                CREATE TABLE wrs_api_championstat_na1 PARTITION OF wrs_api_championstat FOR VALUES IN ('na1');
                CREATE TABLE wrs_api_championstat_br1 PARTITION OF wrs_api_championstat FOR VALUES IN ('br1');
                CREATE TABLE wrs_api_championstat_euw1 PARTITION OF wrs_api_championstat FOR VALUES IN ('euw1');

                CREATE INDEX wrs_api_championstat_championId_c231a738 ON wrs_api_championstat ("championId");
                CREATE INDEX wrs_api_championstat_patch_db5180eb ON wrs_api_championstat ("patch");
                CREATE INDEX wrs_api_championstat_patch__db5180eb_like ON wrs_api_championstat ("patch" varchar_pattern_ops);
                CREATE INDEX wrs_api_championstat_platform_88d7ca7a ON wrs_api_championstat ("platform");
                CREATE INDEX wrs_api_championstat_platform_88d7ca7a_like ON wrs_api_championstat ("platform" varchar_pattern_ops);
                CREATE INDEX wrs_api_championstat_season_id_24005562 ON wrs_api_championstat ("season_id");
            """
        )
    ]
