# Generated by Django 4.2.7 on 2024-04-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrs_api', '0002_championstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuiltFirstStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
            ],
            options={
                'db_table': 'wrs_api_builtfirststat',
                'managed': False,
            },
        ),
        migrations.RunSQL(
            """
                CREATE TABLE wrs_api_builtfirststat (
                    "id" SERIAL NOT NULL,
                    "wins" INTEGER NOT NULL,
                    "losses" INTEGER NOT NULL,
                    "championId" INTEGER NOT NULL,
                    "legendary_item" INTEGER NOT NULL,
                    "patch" VARCHAR(25) NOT NULL,
                    "platform" VARCHAR NOT NULL,
                    "season_id" BIGINT NOT NULL,
                    CONSTRAINT wrs_api_builtfirststat_legendary_item_platfo_19af9e7d_uniq UNIQUE ("legendary_item", "platform", "patch"),
                    FOREIGN KEY ("championId") REFERENCES wrs_api_champion ("championId") ON DELETE DEFERRABLE INITIALLY DEFERRED,
                    FOREIGN KEY ("legendary_item") REFERENCES wrs_api_legendaryitem ("itemId") ON DELETE DEFERRABLE INITIALLY DEFERRED,
                    FOREIGN KEY ("patch") REFERENCES wrs_api_patch ("full_version") ON DELETE DEFERRABLE INITIALLY DEFERRED,
                    FOREIGN KEY ("platform") REFERENCES wrs_api_platform ("code") ON DELETE DEFERRABLE INITIALLY DEFERRED,
                    FOREIGN KEY ("season_id") REFERENCES wrs_api_season ("id") ON DELETE DEFERRABLE INITIALLY DEFERRED,
                    PRIMARY KEY ("platform","championId","patch")
                ) PARTITION BY LIST ("platform");

                CREATE INDEX wrs_api_builtfirststat_championId_37f26e8d ON wrs_api_builtfirststat ("championId");
                CREATE INDEX wrs_api_builtfirststat_legendary_item_e24cdaad ON wrs_api_builtfirststat ("legendary_item");
                CREATE INDEX wrs_api_builtfirststat_patch_a2f5b0fa ON wrs_api_builtfirststat ("patch");
                CREATE INDEX wrs_api_builtfirststat_patch_a2f5b0fa_like ON wrs_api_builtfirststat ("patch" varchar_pattern_ops);
                CREATE INDEX wrs_api_builtfirststat_platform_83170699 ON wrs_api_builtfirststat ("platform");
                CREATE INDEX wrs_api_builtfirststat_platform_83170699_like ON wrs_api_builtfirststat ("platform" varchar_pattern_ops);
                CREATE INDEX wrs_api_builtfirststat_season_id_e2eb2542 ON wrs_api_builtfirststat ("season_id");

                CREATE TABLE wrs_api_builtfirststat_na1 PARTITION OF wrs_api_builtfirststat FOR VALUES IN ('na1');
                CREATE TABLE wrs_api_builtfirststat_br1 PARTITION OF wrs_api_builtfirststat FOR VALUES IN ('br1');
                CREATE TABLE wrs_api_builtfirststat_euw1 PARTITION OF wrs_api_builtfirststat FOR VALUES IN ('euw1');
            """
        )
    ]
