# Generated by Django 4.2.7 on 2024-01-16 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('split', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puuid', models.CharField(max_length=100)),
                ('gameName', models.CharField(max_length=50)),
                ('tagLine', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=40)),
                ('profileIconId', models.IntegerField(blank=True)),
                ('encryptedSummonerId', models.CharField(max_length=100)),
                ('summonerName', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SummonerOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.JSONField(default=dict)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overviews', to='wrs_api.season')),
                ('summoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overviews', to='wrs_api.summoner')),
            ],
            options={
                'unique_together': {('season', 'summoner')},
            },
        ),
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_match_history', models.JSONField(default=list)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='wrs_api.season')),
                ('summoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='wrs_api.summoner')),
            ],
            options={
                'unique_together': {('season', 'summoner')},
            },
        ),
    ]
