# Generated by Django 4.2.7 on 2024-05-29 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wrs_api', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(sql=[
            """
            --- Model PersonalChampStat
            --- Model PersonalChampStat
            --- Model PersonalChampStat
            CREATE TABLE "wrs_api_personalchampstat" (
                "id" SERIAL NOT NULL,
                "games" integer NOT NULL,
                "wins" integer NOT NULL,
                "losses" integer NOT NULL,
                "kills" integer NOT NULL,
                "deaths" integer NOT NULL,
                "assists" integer NOT NULL,
                "cs" integer NOT NULL,
                "csm" double precision NOT NULL,
                "championId" integer NOT NULL,
                "platform" varchar NOT NULL,
                "puuid" varchar(100) NOT NULL,
                "queueId" integer NOT NULL,
                "season_id" bigint NOT NULL,
                FOREIGN KEY ("platform", "puuid") REFERENCES wrs_api_summoner ("platform", "puuid") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                FOREIGN KEY ("championId") REFERENCES "wrs_api_champion" ("championId") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                FOREIGN KEY ("platform") REFERENCES "wrs_api_platform" ("code") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                FOREIGN KEY ("queueId") REFERENCES "wrs_api_gamemode" ("queueId") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                FOREIGN KEY ("season_id") REFERENCES "wrs_api_season" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                UNIQUE ("puuid", "platform", "championId", "season_id"),
                PRIMARY KEY ("puuid", "platform", "championId", "season_id")
            ) PARTITION BY LIST (platform);

            CREATE TABLE wrs_api_personalchampstat_na1 PARTITION OF wrs_api_personalchampstat FOR VALUES IN ('na1');
            CREATE TABLE wrs_api_personalchampstat_euw1 PARTITION OF wrs_api_personalchampstat FOR VALUES IN ('euw1');
            CREATE TABLE wrs_api_personalchampstat_br1 PARTITION OF wrs_api_personalchampstat FOR VALUES IN ('br1');

            CREATE INDEX "wrs_api_personalchampstat_championId_42f4dc50" ON "wrs_api_personalchampstat" ("championId");
            CREATE INDEX "wrs_api_personalchampstat_platform_caad96b6" ON "wrs_api_personalchampstat" ("platform");
            CREATE INDEX "wrs_api_personalchampstat_puuid_d9238503" ON "wrs_api_personalchampstat" ("puuid");
            CREATE INDEX "wrs_api_personalchampstat_queueId_fc3069d0" ON "wrs_api_personalchampstat" ("queueId");
            CREATE INDEX "wrs_api_personalchampstat_season_id_b969eb55" ON "wrs_api_personalchampstat" ("season_id");


            --- Model PreferredRole
            --- Model PreferredRole
            --- Model PreferredRole
            CREATE TABLE "wrs_api_preferredrole" (
                "id" SERIAL NOT NULL,
                "puuid" varchar(100) NOT NULL,
                "top" integer NOT NULL,
                "jungle" integer NOT NULL,
                "middle" integer NOT NULL,
                "bottom" integer NOT NULL,
                "support" integer NOT NULL,
                "platform" varchar NOT NULL,
                "season_id" bigint NOT NULL,
                FOREIGN KEY (platform, puuid) REFERENCES wrs_api_summoner (platform, puuid) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                FOREIGN KEY (season_id) REFERENCES wrs_api_season (id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                FOREIGN KEY ("platform") REFERENCES wrs_api_platform ("code") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                UNIQUE ("puuid", "platform", "season_id"),
                PRIMARY KEY ("puuid", "platform", "season_id")
            ) PARTITION BY LIST (platform);

            CREATE TABLE wrs_api_preferredrole_na1 PARTITION OF wrs_api_preferredrole FOR VALUES IN ('na1');
            CREATE TABLE wrs_api_preferredrole_euw1 PARTITION OF wrs_api_preferredrole FOR VALUES IN ('euw1');
            CREATE TABLE wrs_api_preferredrole_br1 PARTITION OF wrs_api_preferredrole FOR VALUES IN ('br1');

            CREATE INDEX "wrs_api_preferredrole_platform_23c148d5" ON "wrs_api_preferredrole" ("platform");
            CREATE INDEX "wrs_api_preferredrole_puuid_2de7d9c0" ON "wrs_api_preferredrole" ("puuid");
            CREATE INDEX "wrs_api_preferredrole_season_id_2b41505f" ON "wrs_api_preferredrole" ("season_id");
            """],
            reverse_sql=[
                """
                    DROP TABLE IF EXISTS wrs_api_personalchampstat CASCADE;
                    DROP TABLE IF EXISTS wrs_api_preferredrole CASCADE;       
                """
            ]
        )

    ]
