# Generated by Django 4.2.7 on 2023-12-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrs_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoneroverview',
            name='region',
            field=models.CharField(default='NA', max_length=200),
            preserve_default=False,
        ),
    ]
