# Generated by Django 4.2.7 on 2024-01-12 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrs_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summoner',
            old_name='encrypted_summoner_id',
            new_name='encryptedSummonerId',
        ),
        migrations.RenameField(
            model_name='summoner',
            old_name='profile_icon_id',
            new_name='profileIconId',
        ),
    ]
