# Generated by Django 4.2.7 on 2024-02-07 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wrs_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchhistory',
            old_name='all_match_history',
            new_name='json',
        ),
        migrations.RenameField(
            model_name='summoneroverview',
            old_name='overview',
            new_name='json',
        ),
        migrations.AlterField(
            model_name='summoneroverview',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summoner_overviews', to='wrs_api.season'),
        ),
        migrations.AlterField(
            model_name='summoneroverview',
            name='summoner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summoner_overviews', to='wrs_api.summoner'),
        ),
        migrations.CreateModel(
            name='MatchDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.JSONField(default=list)),
                ('summoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_details', to='wrs_api.summoner')),
            ],
        ),
    ]
