# Generated by Django 4.2.7 on 2024-06-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrs_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riotapiversion',
            name='name',
        ),
        migrations.AddField(
            model_name='riotapiversion',
            name='asset',
            field=models.CharField(default='n/a', max_length=30, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riotapiversion',
            name='version',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
