# Generated by Django 4.2.7 on 2024-02-07 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wrs_api', '0002_rename_all_match_history_matchhistory_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchdetails',
            name='summoner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_details', to='wrs_api.summoner'),
        ),
    ]
