# Generated by Django 4.2.7 on 2023-12-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrs_api', '0002_summoneroverview_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.CharField(max_length=50)),
                ('tagLine', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=200)),
                ('metadata', models.JSONField(default=list)),
            ],
        ),
    ]
