# Generated by Django 4.2.7 on 2023-12-14 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrs_api', '0003_matchhistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='summoneroverview',
            unique_together={('gameName', 'tagLine', 'region')},
        ),
    ]
