# Generated by Django 4.2.7 on 2023-12-14 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrs_api', '0004_alter_summoneroverview_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchhistory',
            unique_together={('gameName', 'tagLine', 'region')},
        ),
    ]
