# Generated by Django 4.2.7 on 2023-12-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrs_api', '0005_alter_matchhistory_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchhistory',
            old_name='metadata',
            new_name='history',
        ),
        migrations.RemoveField(
            model_name='summoneroverview',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='summoneroverview',
            name='freshBlood',
        ),
        migrations.RemoveField(
            model_name='summoneroverview',
            name='hotStreak',
        ),
        migrations.RemoveField(
            model_name='summoneroverview',
            name='inactive',
        ),
        migrations.RemoveField(
            model_name='summoneroverview',
            name='leagueId',
        ),
        migrations.RemoveField(
            model_name='summoneroverview',
            name='leaguePoints',
        ),
        migrations.RemoveField(
            model_name='summoneroverview',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='summoneroverview',
            name='profileIcon',
        ),
        migrations.RemoveField(
            model_name='summoneroverview',
            name='queueType',
        ),
        migrations.RemoveField(
            model_name='summoneroverview',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='summoneroverview',
            name='summonerId',
        ),
        migrations.RemoveField(
            model_name='summoneroverview',
            name='summonerName',
        ),
        migrations.RemoveField(
            model_name='summoneroverview',
            name='tier',
        ),
        migrations.RemoveField(
            model_name='summoneroverview',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='summoneroverview',
            name='veteran',
        ),
        migrations.RemoveField(
            model_name='summoneroverview',
            name='wins',
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='puuid',
            field=models.CharField(default='NA', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summoneroverview',
            name='overview',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='matchhistory',
            name='region',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='summoneroverview',
            name='puuid',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='summoneroverview',
            name='region',
            field=models.CharField(max_length=50),
        ),
    ]
