# Generated by Django 4.2.7 on 2024-01-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrs_api', '0006_rename_metadata_matchhistory_history_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankedLpHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.CharField(max_length=50)),
                ('tagLine', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=50)),
                ('puuid', models.CharField(max_length=200, unique=True)),
                ('lp_history', models.JSONField(default=list)),
            ],
        ),
    ]
